// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.6.1
// source: dayhan.proto

package dayhanGrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	DayhanGrpc_GetProductList_FullMethodName = "/dayhanGrpc.DayhanGrpc/GetProductList"
)

// DayhanGrpcClient is the client API for DayhanGrpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DayhanGrpcClient interface {
	GetProductList(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*ProductListResponse, error)
}

type dayhanGrpcClient struct {
	cc grpc.ClientConnInterface
}

func NewDayhanGrpcClient(cc grpc.ClientConnInterface) DayhanGrpcClient {
	return &dayhanGrpcClient{cc}
}

func (c *dayhanGrpcClient) GetProductList(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*ProductListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProductListResponse)
	err := c.cc.Invoke(ctx, DayhanGrpc_GetProductList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DayhanGrpcServer is the server API for DayhanGrpc service.
// All implementations must embed UnimplementedDayhanGrpcServer
// for forward compatibility
type DayhanGrpcServer interface {
	GetProductList(context.Context, *EmptyRequest) (*ProductListResponse, error)
	mustEmbedUnimplementedDayhanGrpcServer()
}

// UnimplementedDayhanGrpcServer must be embedded to have forward compatible implementations.
type UnimplementedDayhanGrpcServer struct {
}

func (UnimplementedDayhanGrpcServer) GetProductList(context.Context, *EmptyRequest) (*ProductListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductList not implemented")
}
func (UnimplementedDayhanGrpcServer) mustEmbedUnimplementedDayhanGrpcServer() {}

// UnsafeDayhanGrpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DayhanGrpcServer will
// result in compilation errors.
type UnsafeDayhanGrpcServer interface {
	mustEmbedUnimplementedDayhanGrpcServer()
}

func RegisterDayhanGrpcServer(s grpc.ServiceRegistrar, srv DayhanGrpcServer) {
	s.RegisterService(&DayhanGrpc_ServiceDesc, srv)
}

func _DayhanGrpc_GetProductList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DayhanGrpcServer).GetProductList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DayhanGrpc_GetProductList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DayhanGrpcServer).GetProductList(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DayhanGrpc_ServiceDesc is the grpc.ServiceDesc for DayhanGrpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DayhanGrpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dayhanGrpc.DayhanGrpc",
	HandlerType: (*DayhanGrpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProductList",
			Handler:    _DayhanGrpc_GetProductList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dayhan.proto",
}
