name: dayhan_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # state management
  flutter_bloc: ^8.1.5

  # router
  go_router: ^13.2.2

  # network
  dartz: ^0.10.1
  http: ^1.2.0

  # core
  cupertino_icons: ^1.0.2

  # json
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1

  # cache
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3

  # Firebase
  
  # cloud

  # animations
  shimmer_animation: ^2.1.0+1
  lottie: ^3.0.0

  # image
  flutter_native_splash: ^2.3.10
  flutter_svg: ^2.0.9

  # file sender

  # map
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
  build_runner: ^2.4.9
  hive_generator: ^2.0.1
  flutter_gen_runner: ^5.4.0

  # json
  json_serializable: ^6.7.1
  freezed: ^2.4.7
  # launcher icons
  # flutter_launcher_icons


flutter_gen:
  output: lib/src/src/utils/assets/
  line_length: 80 

  # Optional
  integrations:
    flutter_svg: true
    # flare_flutter: true
    # rive: true
    lottie: true

  # colors:
  #   inputs:
  #     - assets/color/colors.xml

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/