environment: production
http_port: 9999
host: "127.0.0.3"
# for web cors port number
chrome_port: 50514

db_url: postgresql://root:password@localhost:5433/dayhan_db?sslmode=disable

rds_addr: localhost:6380
rds_pas:
rds_db: 0

auth_key: "i45u934ujfskdmflfsdkfweuut934utjksdfksmdkfmdkfhsdherwreurugttfdbsbsfhgwyrt7324wefhbdbfshdfgysdgf783t32grbfdsn"
user_key: "hbgrehgeknjergb84983rhjfh384yt3u4hg83unu3g2h3hfn923fh283fn23ugf273gbfy3g893h4bfu344374h3f34gf34gf2ihe2ijwj2je"