# Redis image Data
FROM redis:latest
EXPOSE 6379
CMD ["redis-server"]



# Postgres image data 
FROM postgres:16-alpine
ENV POSTGRES_DB=dayhan_db
ENV POSTGRES_PASSWORD=password
ENV POSTGRES_USER=root
EXPOSE 5432
CMD [ "postgres", "-D", "/var/lib/postgresql/data" ]